server:
  port: 8080
#  servlet:
#    context-path: /auth-server

spring:
  # 路径匹配机制
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # 数据库
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ExorcistUser
      username: Admin
      password: 123456

mybatis:
  #type-aliases-package: com.exorcist.pojo
  #mapper-locations: classpath:com.game.server.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# swagger-ui
springdoc:
  swagger-ui:
    path : /swagger-ui.html
